# Generated by Django 5.0.4 on 2024-04-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Niveau', models.IntegerField()),
                ('Hp', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Attaque', models.IntegerField()),
                ('Defense', models.IntegerField()),
                ('Vitesse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
            ],
        ),
    ]
