# Generated by Django 5.0.4 on 2024-04-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('tc', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('points_forts', models.ManyToManyField(related_name='points_faibles', to='pokemon_app.type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50, unique=True)),
                ('Hp', models.IntegerField(null=True)),
                ('Experience', models.IntegerField(null=True)),
                ('Attaque', models.IntegerField(null=True)),
                ('Defense', models.IntegerField(null=True)),
                ('Vitesse', models.IntegerField(null=True)),
                ('Image', models.CharField(max_length=500)),
                ('evolves_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_to', to='pokemon_app.pokemon')),
                ('talents', models.ManyToManyField(to='pokemon_app.talent')),
                ('types', models.ManyToManyField(to='pokemon_app.type')),
            ],
        ),
    ]
